name: Update Discord Bot

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: [self-hosted, linux, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: |
          cd /home/pi/promoscraper
          /home/pi/promoscraper/venv/bin/pip install -r requirements.txt

      - name: Restart Discord Bot
        run: sudo systemctl restart discordbot.service
