name: Update Discord Bot

on:
  push:
    branches: [main]

jobs:
  update:
    runs-on: [self-hosted, linux, arm64]
    steps:
      - uses: actions/checkout@v3
      - name: Pull latest changes
        run: git pull
      - name: Restart Discord Bot
        run: sudo systemctl restart discordbot.service
